// <auto-generated />
namespace ProjectForecast_OA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _10315 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10315));
        
        string IMigrationMetadata.Id
        {
            get { return "201910311028530_1031-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
