// <auto-generated />
namespace ProjectForecast_OA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11041 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11041));
        
        string IMigrationMetadata.Id
        {
            get { return "201911040811186_1104-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
