// <auto-generated />
namespace ProjectForecast_OA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11013));
        
        string IMigrationMetadata.Id
        {
            get { return "201911010653204_1101-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
